### PR TITLE
Improve Github workflow

### PR DESCRIPTION
**Pull request by truita**
This PR groups some actions (such as installing deps) and adds cache to the toolchain so it doesn't rebuild every time

### CODE REVIEW

**Comment by Arnau478** [comment]
I don't really like that the cache key is `toolchain-1`... Any way to fix that?
Apart from that, really cool and necessary!

**Comment by truita** [comment]
There isn't a way to clear caches, so the 1 is an increment for updates. If you can in the future it's pretty easy to change though

**Comment by Arnau478** [comment]
Wouldn't be easier to just save it as one unique cache and overwrite it when we update the toolchain? There is no need to delete it, just to overwrite it

**Comment by truita** [comment]
I'll make another manually triggered CI for it then

**Review by Arnau478 — APPROVED** [review]
Seems all right

**Pull request merged**
